// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhcddkfgqhwwfvqymqow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoY2Rka2ZncWh3d2Z2cXltcW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjEwMjksImV4cCI6MjA3MTE5NzAyOX0.UbdT92SMYYRCgqFWVx1c9TZ7yUqTAiNdg2tN3yQNgRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});